# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgAltaTipoReparacion.ui'
#
# Created: Fri Jul 18 15:22:55 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

from Utiles_formulario import TablaTiposDeRepuestos
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogAltaTipoReparacion(object):
    def setupUi(self, DialogAltaTipoReparacion):
        DialogAltaTipoReparacion.setObjectName(_fromUtf8("DialogAltaTipoReparacion"))
        DialogAltaTipoReparacion.resize(1221, 568)
        DialogAltaTipoReparacion.setWindowTitle(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Alta Tipo de Reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(DialogAltaTipoReparacion)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DialogAltaTipoReparacion)
        self.groupBox.setTitle(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Nuevo tipo de reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Nombre:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditNombre = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditNombre.sizePolicy().hasHeightForWidth())
        self.lineEditNombre.setSizePolicy(sizePolicy)
        self.lineEditNombre.setToolTip(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Ingrese aquí el nombre de la nueva sección", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditNombre.setObjectName(_fromUtf8("lineEditNombre"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditNombre)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Descripción:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEditDescripcion = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditDescripcion.setMaximumSize(QtCore.QSize(300, 16777215))
        self.lineEditDescripcion.setObjectName(_fromUtf8("lineEditDescripcion"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditDescripcion)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Sección:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.comboBoxSeccion = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxSeccion.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboBoxSeccion.setObjectName(_fromUtf8("comboBoxSeccion"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxSeccion)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Asignar Repuestos", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        spacerItem1 = QtGui.QSpacerItem(20, 45, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.pushButtonAsignarRepuesto = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonAsignarRepuesto.setToolTip(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Haga click aquí para agregar el empleado seleccionado a la sección", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAsignarRepuesto.setWhatsThis(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Agrega el empleado seleccionado a la sección", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAsignarRepuesto.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAsignarRepuesto.setObjectName(_fromUtf8("pushButtonAsignarRepuesto"))
        self.verticalLayout_5.addWidget(self.pushButtonAsignarRepuesto)
        self.pushButtonDesasignarRepuesto = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonDesasignarRepuesto.setToolTip(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Haga click aquí para quitar el empleado seleccionado de la sección", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDesasignarRepuesto.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDesasignarRepuesto.setObjectName(_fromUtf8("pushButtonDesasignarRepuesto"))
        self.verticalLayout_5.addWidget(self.pushButtonDesasignarRepuesto)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
#        self.tableWidgetRepuestosSinAsignar = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetRepuestosSinAsignar = TablaTiposDeRepuestos(self.groupBox_2)
        self.tableWidgetRepuestosSinAsignar.setObjectName(_fromUtf8("tableWidgetRepuestosSinAsignar"))
        self.tableWidgetRepuestosSinAsignar.setColumnCount(3)
        self.tableWidgetRepuestosSinAsignar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRepuestosSinAsignar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRepuestosSinAsignar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRepuestosSinAsignar.setHorizontalHeaderItem(2, item)
        self.tableWidgetRepuestosSinAsignar.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidgetRepuestosSinAsignar, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Repuestos asignados:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
#        self.tableWidgetRepuestosAsignados = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetRepuestosAsignados = TablaTiposDeRepuestos(self.groupBox_2)
        self.tableWidgetRepuestosAsignados.setObjectName(_fromUtf8("tableWidgetRepuestosAsignados"))
        self.tableWidgetRepuestosAsignados.setColumnCount(3)
        self.tableWidgetRepuestosAsignados.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRepuestosAsignados.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetRepuestosAsignados.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Descripción"))
        self.tableWidgetRepuestosAsignados.setHorizontalHeaderItem(2, item)
        self.tableWidgetRepuestosAsignados.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_4.addWidget(self.tableWidgetRepuestosAsignados)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Repuestos sin asignar:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBoxButtonBox = QtGui.QGroupBox(DialogAltaTipoReparacion)
        self.groupBoxButtonBox.setMinimumSize(QtCore.QSize(271, 41))
        self.groupBoxButtonBox.setMaximumSize(QtCore.QSize(16777215, 41))
        self.groupBoxButtonBox.setTitle(_fromUtf8(""))
        self.groupBoxButtonBox.setObjectName(_fromUtf8("groupBoxButtonBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBoxButtonBox)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButtonAceptar = QtGui.QPushButton(self.groupBoxButtonBox)
        self.pushButtonAceptar.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.gridLayout_2.addWidget(self.pushButtonAceptar, 0, 1, 1, 1)
        self.pushButtonCancelar = QtGui.QPushButton(self.groupBoxButtonBox)
        self.pushButtonCancelar.setText(QtGui.QApplication.translate("DialogAltaTipoReparacion", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.gridLayout_2.addWidget(self.pushButtonCancelar, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxButtonBox)

        self.retranslateUi(DialogAltaTipoReparacion)
        QtCore.QObject.connect(self.pushButtonAceptar, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogAltaTipoReparacion.accept)
        QtCore.QObject.connect(self.pushButtonCancelar, QtCore.SIGNAL(_fromUtf8("clicked()")), DialogAltaTipoReparacion.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAltaTipoReparacion)

    def retranslateUi(self, DialogAltaTipoReparacion):
        item = self.tableWidgetRepuestosSinAsignar.horizontalHeaderItem(0)
        item = self.tableWidgetRepuestosSinAsignar.horizontalHeaderItem(1)
        item = self.tableWidgetRepuestosSinAsignar.horizontalHeaderItem(2)
        item = self.tableWidgetRepuestosAsignados.horizontalHeaderItem(0)
        item = self.tableWidgetRepuestosAsignados.horizontalHeaderItem(1)
        item = self.tableWidgetRepuestosAsignados.horizontalHeaderItem(2)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DialogAltaTipoReparacion = QtGui.QDialog()
    ui = Ui_DialogAltaTipoReparacion()
    ui.setupUi(DialogAltaTipoReparacion)
    DialogAltaTipoReparacion.show()
    sys.exit(app.exec_())

