# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgFinalizarTurno.ui'
#
# Created: Tue Jul 29 22:49:16 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

from Utiles_formulario import TablaReparaciones, TablaEmpleadosSeccion
class Ui_DialogoFinalizarTurno(object):
    def setupUi(self, DialogoFinalizarTurno):
        DialogoFinalizarTurno.setObjectName(_fromUtf8("DialogoFinalizarTurno"))
        DialogoFinalizarTurno.resize(822, 600)
        DialogoFinalizarTurno.setWindowTitle(QtGui.QApplication.translate("DialogoFinalizarTurno", "Finalizar reparaciones del turno", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(DialogoFinalizarTurno)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DialogoFinalizarTurno)
        self.groupBox.setTitle(QtGui.QApplication.translate("DialogoFinalizarTurno", "Seleccionar turno de la Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelFecha = QtGui.QLabel(self.groupBox)
        self.labelFecha.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Fecha:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFecha.setObjectName(_fromUtf8("labelFecha"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelFecha)
        self.comboBoxFecha = QtGui.QComboBox(self.groupBox)
        self.comboBoxFecha.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxFecha.setObjectName(_fromUtf8("comboBoxFecha"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxFecha)
        self.labelHora = QtGui.QLabel(self.groupBox)
        self.labelHora.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Hora:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelHora.setObjectName(_fromUtf8("labelHora"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHora)
        self.comboBoxHora = QtGui.QComboBox(self.groupBox)
        self.comboBoxHora.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxHora.setObjectName(_fromUtf8("comboBoxHora"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxHora)
        self.labelVehiculo = QtGui.QLabel(self.groupBox)
        self.labelVehiculo.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Vehículo:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelVehiculo.setObjectName(_fromUtf8("labelVehiculo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelVehiculo)
        self.labelDominio = QtGui.QLabel(self.groupBox)
        self.labelDominio.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "DOMINIO", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDominio.setObjectName(_fromUtf8("labelDominio"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelDominio)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.labelReparaciones = QtGui.QLabel(self.groupBox)
        self.labelReparaciones.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Reparaciones:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReparaciones.setObjectName(_fromUtf8("labelReparaciones"))
        self.verticalLayout_3.addWidget(self.labelReparaciones)
#        self.tableWidgetReparaciones = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetReparaciones = TablaReparaciones(self.groupBox)
        self.tableWidgetReparaciones.setObjectName(_fromUtf8("tableWidgetReparaciones"))
        self.tableWidgetReparaciones.setColumnCount(3)
        self.tableWidgetReparaciones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "CODIGO", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "NOMBRE", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "DESCRIPCION", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(2, item)
        self.verticalLayout_3.addWidget(self.tableWidgetReparaciones)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Empleados asignados", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
#        self.tableWidgetEmpleados = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetEmpleados = TablaEmpleadosSeccion(self.groupBox)
        self.tableWidgetEmpleados.setObjectName(_fromUtf8("tableWidgetEmpleados"))
        self.tableWidgetEmpleados.setColumnCount(6)
        self.tableWidgetEmpleados.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "NOMBRE", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "APELLIDO", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "T.DOC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "N.DOC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "F.NAC", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "EMAIL", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetEmpleados.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidgetEmpleados)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(DialogoFinalizarTurno)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DialogoFinalizarTurno", "Finalizar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Observaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.plainTextEditObservaciones = QtGui.QPlainTextEdit(self.groupBox_2)
        self.plainTextEditObservaciones.setObjectName(_fromUtf8("plainTextEditObservaciones"))
        self.verticalLayout_6.addWidget(self.plainTextEditObservaciones)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButtonFinalizar = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonFinalizar.setText(QtGui.QApplication.translate("DialogoFinalizarTurno", "Finalizar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonFinalizar.setObjectName(_fromUtf8("pushButtonFinalizar"))
        self.horizontalLayout_4.addWidget(self.pushButtonFinalizar)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.buttonBox = QtGui.QDialogButtonBox(DialogoFinalizarTurno)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogoFinalizarTurno)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogoFinalizarTurno.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogoFinalizarTurno.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogoFinalizarTurno)

    def retranslateUi(self, DialogoFinalizarTurno):
        item = self.tableWidgetReparaciones.horizontalHeaderItem(0)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(1)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(2)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(0)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(1)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(2)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(3)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(4)
        item = self.tableWidgetEmpleados.horizontalHeaderItem(5)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DialogoFinalizarTurno = QtGui.QDialog()
    ui = Ui_DialogoFinalizarTurno()
    ui.setupUi(DialogoFinalizarTurno)
    DialogoFinalizarTurno.show()
    sys.exit(app.exec_())

