# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DlgFinalizarTurno.ui'
#
# Created: Thu Sep 18 02:10:27 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

from Utiles_formulario import TablaReparaciones, TablaEmpleadosSeccion


class Ui_DialogoFinalizarTurno(object):
    def setupUi(self, DialogoFinalizarTurno):
        DialogoFinalizarTurno.setObjectName(_fromUtf8("DialogoFinalizarTurno"))
        DialogoFinalizarTurno.resize(822, 600)
        self.verticalLayout = QtGui.QVBoxLayout(DialogoFinalizarTurno)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DialogoFinalizarTurno)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelFecha = QtGui.QLabel(self.groupBox)
        self.labelFecha.setObjectName(_fromUtf8("labelFecha"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelFecha)
        self.comboBoxFecha = QtGui.QComboBox(self.groupBox)
        self.comboBoxFecha.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxFecha.setObjectName(_fromUtf8("comboBoxFecha"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.comboBoxFecha)
        self.labelHora = QtGui.QLabel(self.groupBox)
        self.labelHora.setObjectName(_fromUtf8("labelHora"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelHora)
        self.comboBoxHora = QtGui.QComboBox(self.groupBox)
        self.comboBoxHora.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxHora.setObjectName(_fromUtf8("comboBoxHora"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxHora)
        self.labelVehiculo = QtGui.QLabel(self.groupBox)
        self.labelVehiculo.setObjectName(_fromUtf8("labelVehiculo"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelVehiculo)
        self.labelDominio = QtGui.QLabel(self.groupBox)
        self.labelDominio.setObjectName(_fromUtf8("labelDominio"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelDominio)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.labelReparaciones = QtGui.QLabel(self.groupBox)
        self.labelReparaciones.setObjectName(_fromUtf8("labelReparaciones"))
        self.verticalLayout_3.addWidget(self.labelReparaciones)
#         self.tableWidgetReparaciones = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetReparaciones = TablaReparaciones(self.groupBox)
        self.tableWidgetReparaciones.setObjectName(_fromUtf8("tableWidgetReparaciones"))
        self.tableWidgetReparaciones.setColumnCount(3)
        self.tableWidgetReparaciones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparaciones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparaciones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparaciones.setHorizontalHeaderItem(2, item)
        self.tableWidgetReparaciones.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidgetReparaciones)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
#         self.tableWidgetEmpleados = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetEmpleados = TablaEmpleadosSeccion(self.groupBox)
        self.tableWidgetEmpleados.setObjectName(_fromUtf8("tableWidgetEmpleados"))
        self.tableWidgetEmpleados.setColumnCount(6)
        self.tableWidgetEmpleados.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetEmpleados.setHorizontalHeaderItem(5, item)
        self.tableWidgetEmpleados.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.tableWidgetEmpleados)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(DialogoFinalizarTurno)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.plainTextEditObservaciones = QtGui.QPlainTextEdit(self.groupBox_2)
        self.plainTextEditObservaciones.setObjectName(_fromUtf8("plainTextEditObservaciones"))
        self.verticalLayout_6.addWidget(self.plainTextEditObservaciones)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pushButtonFinalizar = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonFinalizar.setObjectName(_fromUtf8("pushButtonFinalizar"))
        self.horizontalLayout_4.addWidget(self.pushButtonFinalizar)
        self.pushButtonSalir = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonSalir.setObjectName(_fromUtf8("pushButtonSalir"))
        self.horizontalLayout_4.addWidget(self.pushButtonSalir)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(DialogoFinalizarTurno)
        QtCore.QMetaObject.connectSlotsByName(DialogoFinalizarTurno)

    def retranslateUi(self, DialogoFinalizarTurno):
        DialogoFinalizarTurno.setWindowTitle(_translate("DialogoFinalizarTurno", "Finalizar reparaciones del turno", None))
        self.groupBox.setTitle(_translate("DialogoFinalizarTurno", "Seleccionar turno de la Sección", None))
        self.labelFecha.setText(_translate("DialogoFinalizarTurno", "Fecha:", None))
        self.labelHora.setText(_translate("DialogoFinalizarTurno", "Hora:", None))
        self.labelVehiculo.setText(_translate("DialogoFinalizarTurno", "Vehículo:", None))
        self.labelDominio.setText(_translate("DialogoFinalizarTurno", "DOMINIO", None))
        self.labelReparaciones.setText(_translate("DialogoFinalizarTurno", "Reparaciones:", None))
        item = self.tableWidgetReparaciones.horizontalHeaderItem(0)
        item.setText(_translate("DialogoFinalizarTurno", "CÓDIGO", None))
        item = self.tableWidgetReparaciones.horizontalHeaderItem(1)
        item.setText(_translate("DialogoFinalizarTurno", "NOMBRE", None))
        item = self.tableWidgetReparaciones.horizontalHeaderItem(2)
        item.setText(_translate("DialogoFinalizarTurno", "DESCRIPCIÓN", None))
        self.label.setText(_translate("DialogoFinalizarTurno", "Empleados asignados", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(0)
        item.setText(_translate("DialogoFinalizarTurno", "NOMBRE", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(1)
        item.setText(_translate("DialogoFinalizarTurno", "APELLIDO", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(2)
        item.setText(_translate("DialogoFinalizarTurno", "T.DOC", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(3)
        item.setText(_translate("DialogoFinalizarTurno", "N.DOC", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(4)
        item.setText(_translate("DialogoFinalizarTurno", "F.NAC", None))
        item = self.tableWidgetEmpleados.horizontalHeaderItem(5)
        item.setText(_translate("DialogoFinalizarTurno", "EMAIL", None))
        self.groupBox_2.setTitle(_translate("DialogoFinalizarTurno", "Finalizar", None))
        self.label_2.setText(_translate("DialogoFinalizarTurno", "Observaciones", None))
        self.pushButtonFinalizar.setText(_translate("DialogoFinalizarTurno", "Finalizar", None))
        self.pushButtonSalir.setText(_translate("DialogoFinalizarTurno", "Salir", None))

