# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/DlgPlanificar.ui'
#
# Created: Mon Oct 20 20:04:15 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

from Utiles_formulario import TablaReparaciones

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogPlanificar(object):
    def setupUi(self, DialogPlanificar):
        DialogPlanificar.setObjectName(_fromUtf8("DialogPlanificar"))
        DialogPlanificar.resize(1059, 603)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/planificar-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DialogPlanificar.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(DialogPlanificar)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(DialogPlanificar)
        self.tabWidget.setWhatsThis(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.formLayout_2 = QtGui.QFormLayout(self.tab1)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelInformacion = QtGui.QLabel(self.tab1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelInformacion.setFont(font)
        self.labelInformacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelInformacion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelInformacion.setIndent(12)
        self.labelInformacion.setObjectName(_fromUtf8("labelInformacion"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelInformacion)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtGui.QFormLayout.LabelRole, spacerItem)
        self.labelSeccion = QtGui.QLabel(self.tab1)
        self.labelSeccion.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelSeccion.setFont(font)
        self.labelSeccion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelSeccion.setIndent(330)
        self.labelSeccion.setObjectName(_fromUtf8("labelSeccion"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelSeccion)
        self.comboBoxSecciones = QtGui.QComboBox(self.tab1)
        self.comboBoxSecciones.setMinimumSize(QtCore.QSize(300, 30))
        self.comboBoxSecciones.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.comboBoxSecciones.setFont(font)
        self.comboBoxSecciones.setObjectName(_fromUtf8("comboBoxSecciones"))
        self.comboBoxSecciones.addItem(_fromUtf8(""))
        self.comboBoxSecciones.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.comboBoxSecciones)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox = QtGui.QGroupBox(self.tab2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelFecha = QtGui.QLabel(self.groupBox_3)
        self.labelFecha.setObjectName(_fromUtf8("labelFecha"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelFecha)
        self.dateEditFechaTurno = QtGui.QDateEdit(self.groupBox_3)
        self.dateEditFechaTurno.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEditFechaTurno.setObjectName(_fromUtf8("dateEditFechaTurno"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEditFechaTurno)
        self.labelHora = QtGui.QLabel(self.groupBox_3)
        self.labelHora.setObjectName(_fromUtf8("labelHora"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelHora)
        self.comboBoxHoraTurno = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxHoraTurno.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxHoraTurno.setObjectName(_fromUtf8("comboBoxHoraTurno"))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.comboBoxHoraTurno.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.comboBoxHoraTurno)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(20, 3, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem2)
        spacerItem3 = QtGui.QSpacerItem(20, 45, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.pushButtonAsignarReparacion = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonAsignarReparacion.setObjectName(_fromUtf8("pushButtonAsignarReparacion"))
        self.verticalLayout_5.addWidget(self.pushButtonAsignarReparacion)
        self.pushButtonDesasignarReparacion = QtGui.QPushButton(self.groupBox_4)
        self.pushButtonDesasignarReparacion.setObjectName(_fromUtf8("pushButtonDesasignarReparacion"))
        self.verticalLayout_5.addWidget(self.pushButtonDesasignarReparacion)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.gridLayout.addWidget(self.groupBox_4, 1, 1, 1, 1)
#         self.tableWidgetReparacionesSinAsignar = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetReparacionesSinAsignar = TablaReparaciones(self.groupBox_2)
        self.tableWidgetReparacionesSinAsignar.setObjectName(_fromUtf8("tableWidgetReparacionesSinAsignar"))
        self.tableWidgetReparacionesSinAsignar.setColumnCount(3)
        self.tableWidgetReparacionesSinAsignar.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparacionesSinAsignar.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparacionesSinAsignar.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparacionesSinAsignar.setHorizontalHeaderItem(2, item)
        self.tableWidgetReparacionesSinAsignar.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidgetReparacionesSinAsignar, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelReparacionesAsignadas = QtGui.QLabel(self.groupBox_2)
        self.labelReparacionesAsignadas.setObjectName(_fromUtf8("labelReparacionesAsignadas"))
        self.verticalLayout_4.addWidget(self.labelReparacionesAsignadas)
#         self.tableWidgetReparacionesAsignadas = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetReparacionesAsignadas = TablaReparaciones(self.groupBox_2)
        self.tableWidgetReparacionesAsignadas.setObjectName(_fromUtf8("tableWidgetReparacionesAsignadas"))
        self.tableWidgetReparacionesAsignadas.setColumnCount(3)
        self.tableWidgetReparacionesAsignadas.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparacionesAsignadas.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetReparacionesAsignadas.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Descripción"))
        self.tableWidgetReparacionesAsignadas.setHorizontalHeaderItem(2, item)
        self.tableWidgetReparacionesAsignadas.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout_4.addWidget(self.tableWidgetReparacionesAsignadas)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 3, 1, 1)
        self.labelReparaciones = QtGui.QLabel(self.groupBox_2)
        self.labelReparaciones.setObjectName(_fromUtf8("labelReparaciones"))
        self.gridLayout.addWidget(self.labelReparaciones, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.PushButtonCrearTurno = QtGui.QPushButton(self.groupBox)
        self.PushButtonCrearTurno.setMinimumSize(QtCore.QSize(100, 0))
        self.PushButtonCrearTurno.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PushButtonCrearTurno.setAutoRepeat(False)
        self.PushButtonCrearTurno.setObjectName(_fromUtf8("PushButtonCrearTurno"))
        self.horizontalLayout.addWidget(self.PushButtonCrearTurno)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(DialogPlanificar)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogPlanificar)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), DialogPlanificar.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), DialogPlanificar.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPlanificar)

    def retranslateUi(self, DialogPlanificar):
        DialogPlanificar.setWindowTitle(_translate("DialogPlanificar", "Planificar reparaciones", None))
        self.tabWidget.setToolTip(_translate("DialogPlanificar", "Seleccione una seccion.", None))
        self.labelInformacion.setText(_translate("DialogPlanificar", "El vehículo posee reparaciones asignadas a las siguientes secciones.\n"
"Elija una para asignar reparaciones a un turno:", None))
        self.labelSeccion.setText(_translate("DialogPlanificar", "Sección:", None))
        self.comboBoxSecciones.setItemText(0, _translate("DialogPlanificar", "unaSeccion ", None))
        self.comboBoxSecciones.setItemText(1, _translate("DialogPlanificar", "Otra", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("DialogPlanificar", "Seccion", None))
        self.groupBox.setTitle(_translate("DialogPlanificar", "Turno", None))
        self.labelFecha.setText(_translate("DialogPlanificar", "Fecha:", None))
        self.labelHora.setText(_translate("DialogPlanificar", "Hora:", None))
        self.comboBoxHoraTurno.setItemText(0, _translate("DialogPlanificar", "8:00", None))
        self.comboBoxHoraTurno.setItemText(1, _translate("DialogPlanificar", "9:00", None))
        self.comboBoxHoraTurno.setItemText(2, _translate("DialogPlanificar", "10:00", None))
        self.comboBoxHoraTurno.setItemText(3, _translate("DialogPlanificar", "11:00", None))
        self.comboBoxHoraTurno.setItemText(4, _translate("DialogPlanificar", "12:00", None))
        self.comboBoxHoraTurno.setItemText(5, _translate("DialogPlanificar", "16:00", None))
        self.comboBoxHoraTurno.setItemText(6, _translate("DialogPlanificar", "17:00", None))
        self.comboBoxHoraTurno.setItemText(7, _translate("DialogPlanificar", "18:00", None))
        self.comboBoxHoraTurno.setItemText(8, _translate("DialogPlanificar", "19:00", None))
        self.comboBoxHoraTurno.setItemText(9, _translate("DialogPlanificar", "20:00", None))
        self.label.setText(_translate("DialogPlanificar", "Sección:", None))
        self.label_2.setText(_translate("DialogPlanificar", "-", None))
        self.groupBox_2.setTitle(_translate("DialogPlanificar", "Asignar reparaciones al turno", None))
        self.pushButtonAsignarReparacion.setToolTip(_translate("DialogPlanificar", "Haga click aquí para agregar el empleado seleccionado a la sección", None))
        self.pushButtonAsignarReparacion.setWhatsThis(_translate("DialogPlanificar", "Agrega el empleado seleccionado a la sección", None))
        self.pushButtonAsignarReparacion.setText(_translate("DialogPlanificar", ">", None))
        self.pushButtonDesasignarReparacion.setToolTip(_translate("DialogPlanificar", "Haga click aquí para quitar el empleado seleccionado de la sección", None))
        self.pushButtonDesasignarReparacion.setText(_translate("DialogPlanificar", "<", None))
        item = self.tableWidgetReparacionesSinAsignar.horizontalHeaderItem(0)
        item.setText(_translate("DialogPlanificar", "Código", None))
        item = self.tableWidgetReparacionesSinAsignar.horizontalHeaderItem(1)
        item.setText(_translate("DialogPlanificar", "Tipo de Reparación", None))
        item = self.tableWidgetReparacionesSinAsignar.horizontalHeaderItem(2)
        item.setText(_translate("DialogPlanificar", "Descripción", None))
        self.labelReparacionesAsignadas.setText(_translate("DialogPlanificar", "Reparaciones asignadas:", None))
        item = self.tableWidgetReparacionesAsignadas.horizontalHeaderItem(0)
        item.setText(_translate("DialogPlanificar", "Código", None))
        item = self.tableWidgetReparacionesAsignadas.horizontalHeaderItem(1)
        item.setText(_translate("DialogPlanificar", "Tipo de Reparación", None))
        item = self.tableWidgetReparacionesAsignadas.horizontalHeaderItem(2)
        self.labelReparaciones.setText(_translate("DialogPlanificar", "Reparaciones", None))
        self.PushButtonCrearTurno.setText(_translate("DialogPlanificar", "Crear Turno", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("DialogPlanificar", "Asignacion de turnos", None))

import recursos_rc
