# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowExample.ui'
#
# Created: Sun Dec 07 20:02:10 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "División Transporte", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/logoDivisionTransporte.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setTitle(QtGui.QApplication.translate("MainWindow", "&Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuVerificacion_y_Reparacion = QtGui.QMenu(self.menubar)
        self.menuVerificacion_y_Reparacion.setTitle(QtGui.QApplication.translate("MainWindow", "&Verificación y Reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVerificacion_y_Reparacion.setObjectName(_fromUtf8("menuVerificacion_y_Reparacion"))
        self.menuListados_de_Vehiculos = QtGui.QMenu(self.menuVerificacion_y_Reparacion)
        self.menuListados_de_Vehiculos.setTitle(QtGui.QApplication.translate("MainWindow", "&Listados de Vehículos", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/list_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuListados_de_Vehiculos.setIcon(icon1)
        self.menuListados_de_Vehiculos.setObjectName(_fromUtf8("menuListados_de_Vehiculos"))
        self.menuPersonal = QtGui.QMenu(self.menubar)
        self.menuPersonal.setTitle(QtGui.QApplication.translate("MainWindow", "&Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPersonal.setObjectName(_fromUtf8("menuPersonal"))
        self.menuListados_Personal = QtGui.QMenu(self.menuPersonal)
        self.menuListados_Personal.setTitle(QtGui.QApplication.translate("MainWindow", "&Listados Personal", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/list_personal-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuListados_Personal.setIcon(icon2)
        self.menuListados_Personal.setObjectName(_fromUtf8("menuListados_Personal"))
        self.menuRepuestos = QtGui.QMenu(self.menubar)
        self.menuRepuestos.setTitle(QtGui.QApplication.translate("MainWindow", "&Repuestos", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRepuestos.setObjectName(_fromUtf8("menuRepuestos"))
        self.menuListados_de_Repuestos = QtGui.QMenu(self.menuRepuestos)
        self.menuListados_de_Repuestos.setTitle(QtGui.QApplication.translate("MainWindow", "&Listados de Repuestos", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/list1-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuListados_de_Repuestos.setIcon(icon3)
        self.menuListados_de_Repuestos.setObjectName(_fromUtf8("menuListados_de_Repuestos"))
        self.menuSecciones = QtGui.QMenu(self.menubar)
        self.menuSecciones.setTitle(QtGui.QApplication.translate("MainWindow", "&Secciones", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSecciones.setObjectName(_fromUtf8("menuSecciones"))
        self.menuConfiguracion = QtGui.QMenu(self.menubar)
        self.menuConfiguracion.setTitle(QtGui.QApplication.translate("MainWindow", "&Configuración", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfiguracion.setObjectName(_fromUtf8("menuConfiguracion"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setTitle(QtGui.QApplication.translate("MainWindow", "&Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSalir = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/salir-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionSalir.setIcon(icon4)
        self.actionSalir.setText(QtGui.QApplication.translate("MainWindow", "&Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cerrar la aplicación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setStatusTip(QtGui.QApplication.translate("MainWindow", "Cierra la aplicación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cerrar la aplicación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionCambiarDeUsuario = QtGui.QAction(MainWindow)
        self.actionCambiarDeUsuario.setText(QtGui.QApplication.translate("MainWindow", "&Cambiar de Usuario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiarDeUsuario.setObjectName(_fromUtf8("actionCambiarDeUsuario"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setText(QtGui.QApplication.translate("MainWindow", "&Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionAyuda = QtGui.QAction(MainWindow)
        self.actionAyuda.setCheckable(True)
        self.actionAyuda.setText(QtGui.QApplication.translate("MainWindow", "&Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAyuda.setObjectName(_fromUtf8("actionAyuda"))
        self.actionAlta_de_Vehiculo = QtGui.QAction(MainWindow)
        self.actionAlta_de_Vehiculo.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/new_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlta_de_Vehiculo.setIcon(icon5)
        self.actionAlta_de_Vehiculo.setText(QtGui.QApplication.translate("MainWindow", "&Alta de Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Vehiculo.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para crear un nuevo vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Vehiculo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Crea un nuevo vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Vehiculo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para crear un nuevo vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Vehiculo.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+V", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Vehiculo.setObjectName(_fromUtf8("actionAlta_de_Vehiculo"))
        self.actionModificacion_de_Vehiculo = QtGui.QAction(MainWindow)
        self.actionModificacion_de_Vehiculo.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/edit_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModificacion_de_Vehiculo.setIcon(icon6)
        self.actionModificacion_de_Vehiculo.setText(QtGui.QApplication.translate("MainWindow", "&Modificación de Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Vehiculo.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Vehiculo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Modifica los datos de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Vehiculo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Vehiculo.setObjectName(_fromUtf8("actionModificacion_de_Vehiculo"))
        self.actionRegistrar_Ingreso_de_Vehiculo = QtGui.QAction(MainWindow)
        self.actionRegistrar_Ingreso_de_Vehiculo.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/ingreso_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Ingreso_de_Vehiculo.setIcon(icon7)
        self.actionRegistrar_Ingreso_de_Vehiculo.setText(QtGui.QApplication.translate("MainWindow", "&Registrar Ingreso de Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Ingreso_de_Vehiculo.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar el ingreso de un vehículo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Ingreso_de_Vehiculo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Registra el ingreso de un vehículo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Ingreso_de_Vehiculo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar el ingreso de vehículo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Ingreso_de_Vehiculo.setObjectName(_fromUtf8("actionRegistrar_Ingreso_de_Vehiculo"))
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo = QtGui.QAction(MainWindow)
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/reparaciones_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setIcon(icon8)
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setText(QtGui.QApplication.translate("MainWindow", "&Registrar Reparaciones necesarias del Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para  registrar las reparaciones necesarias del vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Registrar las reparaciones necesarias del vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para  registrar las reparaciones necesarias del vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo.setObjectName(_fromUtf8("actionVerificar_Reparaciones_Necesarias_del_Vehiculo"))
        self.actionRegistrar_Egreso = QtGui.QAction(MainWindow)
        self.actionRegistrar_Egreso.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/egreso_car-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRegistrar_Egreso.setIcon(icon9)
        self.actionRegistrar_Egreso.setText(QtGui.QApplication.translate("MainWindow", "&Registrar Egreso Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Egreso.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar el egreso de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Egreso.setStatusTip(QtGui.QApplication.translate("MainWindow", "Registra el egreso de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Egreso.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar el egreso de un vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Egreso.setObjectName(_fromUtf8("actionRegistrar_Egreso"))
        self.actionPlanificar_Reparaciones_de_Vehiculo = QtGui.QAction(MainWindow)
        self.actionPlanificar_Reparaciones_de_Vehiculo.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/planificar-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlanificar_Reparaciones_de_Vehiculo.setIcon(icon10)
        self.actionPlanificar_Reparaciones_de_Vehiculo.setText(QtGui.QApplication.translate("MainWindow", "&Planificar Reparaciones de Vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanificar_Reparaciones_de_Vehiculo.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para  planificar las reparaciones de un vehículo ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanificar_Reparaciones_de_Vehiculo.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite planificar las reparaciones de un vehículo ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanificar_Reparaciones_de_Vehiculo.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para  planificar las reparaciones de un vehículo ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlanificar_Reparaciones_de_Vehiculo.setObjectName(_fromUtf8("actionPlanificar_Reparaciones_de_Vehiculo"))
        self.actionListado_Vehiculos_en_reparacion_por_Seccion = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_en_reparacion_por_Seccion.setText(QtGui.QApplication.translate("MainWindow", "Listado Vehiculos en Reparacion por Seccion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_en_reparacion_por_Seccion.setObjectName(_fromUtf8("actionListado_Vehiculos_en_reparacion_por_Seccion"))
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas.setText(QtGui.QApplication.translate("MainWindow", "Listado Vehiculos con Reparaciones Planificadas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas.setObjectName(_fromUtf8("actionListado_Vehiculos_con_Reparaciones_Planificadas"))
        self.actionListado_Vehiculos_Reparados_por_Seccion = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_Reparados_por_Seccion.setText(QtGui.QApplication.translate("MainWindow", "Listado Vehiculos Reparados por Seccion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_Reparados_por_Seccion.setObjectName(_fromUtf8("actionListado_Vehiculos_Reparados_por_Seccion"))
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos = QtGui.QAction(MainWindow)
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos.setText(QtGui.QApplication.translate("MainWindow", "Listado de Reparaciones Realizadas a un Vehiculos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos.setObjectName(_fromUtf8("actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos"))
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas.setText(QtGui.QApplication.translate("MainWindow", "Listado Vehiculos con Reparaciones no Planificadas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas.setObjectName(_fromUtf8("actionListado_Vehiculos_con_Reparaciones_no_Planificadas"))
        self.actionListado_Vehiculos_de_la_Division_2 = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_de_la_Division_2.setEnabled(False)
        self.actionListado_Vehiculos_de_la_Division_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado Vehículos de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_de_la_Division_2.setObjectName(_fromUtf8("actionListado_Vehiculos_de_la_Division_2"))
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas_2 = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas_2.setEnabled(False)
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado Vehículos con Reparaciones Planificadas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_con_Reparaciones_Planificadas_2.setObjectName(_fromUtf8("actionListado_Vehiculos_con_Reparaciones_Planificadas_2"))
        self.actionListado_Vehiculos_en_Reparacion_por_Seccion = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_en_Reparacion_por_Seccion.setEnabled(False)
        self.actionListado_Vehiculos_en_Reparacion_por_Seccion.setText(QtGui.QApplication.translate("MainWindow", "&Listado Vehículos en Reparación por Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_en_Reparacion_por_Seccion.setObjectName(_fromUtf8("actionListado_Vehiculos_en_Reparacion_por_Seccion"))
        self.actionListado_Vehiculos_Reparados_por_Seccion_2 = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_Reparados_por_Seccion_2.setEnabled(False)
        self.actionListado_Vehiculos_Reparados_por_Seccion_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado Vehículos Reparados por Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_Reparados_por_Seccion_2.setObjectName(_fromUtf8("actionListado_Vehiculos_Reparados_por_Seccion_2"))
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2 = QtGui.QAction(MainWindow)
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2.setEnabled(False)
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado de Reparaciones Realizadas a un Vehículos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2.setObjectName(_fromUtf8("actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2"))
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2 = QtGui.QAction(MainWindow)
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2.setEnabled(False)
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado Vehículos con Reparaciones no Planificadas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2.setObjectName(_fromUtf8("actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2"))
        self.actionAlta_de_Personal = QtGui.QAction(MainWindow)
        self.actionAlta_de_Personal.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/add_person-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlta_de_Personal.setIcon(icon11)
        self.actionAlta_de_Personal.setText(QtGui.QApplication.translate("MainWindow", "&Alta de Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Personal.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Personal.setStatusTip(QtGui.QApplication.translate("MainWindow", "Da de alta a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Personal.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Personal.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Personal.setObjectName(_fromUtf8("actionAlta_de_Personal"))
        self.actionBaja_de_Personal = QtGui.QAction(MainWindow)
        self.actionBaja_de_Personal.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/remove_person-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBaja_de_Personal.setIcon(icon12)
        self.actionBaja_de_Personal.setText(QtGui.QApplication.translate("MainWindow", "&Baja de Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaja_de_Personal.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de baja a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaja_de_Personal.setStatusTip(QtGui.QApplication.translate("MainWindow", "Da de baja a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaja_de_Personal.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de baja a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBaja_de_Personal.setObjectName(_fromUtf8("actionBaja_de_Personal"))
        self.actionModificacion_de_Personal = QtGui.QAction(MainWindow)
        self.actionModificacion_de_Personal.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/modificar_persona-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionModificacion_de_Personal.setIcon(icon13)
        self.actionModificacion_de_Personal.setText(QtGui.QApplication.translate("MainWindow", "&Modificación de Personal", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Personal.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Personal.setStatusTip(QtGui.QApplication.translate("MainWindow", "Modifica los datos de un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Personal.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Personal.setObjectName(_fromUtf8("actionModificacion_de_Personal"))
        self.actionCambiar_de_Seccion_a_un_Empleado = QtGui.QAction(MainWindow)
        self.actionCambiar_de_Seccion_a_un_Empleado.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/change_person-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_de_Seccion_a_un_Empleado.setIcon(icon14)
        self.actionCambiar_de_Seccion_a_un_Empleado.setText(QtGui.QApplication.translate("MainWindow", "&Cambiar de Sección a un Empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_de_Seccion_a_un_Empleado.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cambiar de sección a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_de_Seccion_a_un_Empleado.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite cambiar de sección a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_de_Seccion_a_un_Empleado.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cambiar de sección a un empleado", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_de_Seccion_a_un_Empleado.setObjectName(_fromUtf8("actionCambiar_de_Seccion_a_un_Empleado"))
        self.actionCambiar_el_Encargado_de_una_Seccion = QtGui.QAction(MainWindow)
        self.actionCambiar_el_Encargado_de_una_Seccion.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/cambiar_encargado-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCambiar_el_Encargado_de_una_Seccion.setIcon(icon15)
        self.actionCambiar_el_Encargado_de_una_Seccion.setText(QtGui.QApplication.translate("MainWindow", "&Cambiar el Encargado de una Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_el_Encargado_de_una_Seccion.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cambiar el encargado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_el_Encargado_de_una_Seccion.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite cambiar el encargado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_el_Encargado_de_una_Seccion.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para cambiar el encargado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCambiar_el_Encargado_de_una_Seccion.setObjectName(_fromUtf8("actionCambiar_el_Encargado_de_una_Seccion"))
        self.actionRemover_Empleado_de_Seccion = QtGui.QAction(MainWindow)
        self.actionRemover_Empleado_de_Seccion.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/personal/remove_de_seccion-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemover_Empleado_de_Seccion.setIcon(icon16)
        self.actionRemover_Empleado_de_Seccion.setText(QtGui.QApplication.translate("MainWindow", "&Remover Empleado de Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemover_Empleado_de_Seccion.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para remover un empleado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemover_Empleado_de_Seccion.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite remover un empleado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemover_Empleado_de_Seccion.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para remover un empleado de una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRemover_Empleado_de_Seccion.setObjectName(_fromUtf8("actionRemover_Empleado_de_Seccion"))
        self.actionListado_de_Personal_de_la_Division = QtGui.QAction(MainWindow)
        self.actionListado_de_Personal_de_la_Division.setEnabled(False)
        self.actionListado_de_Personal_de_la_Division.setText(QtGui.QApplication.translate("MainWindow", "&Listado de Personal de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Personal_de_la_Division.setObjectName(_fromUtf8("actionListado_de_Personal_de_la_Division"))
        self.actionListado_de_Personal_sin_Asignar_a_Secciones = QtGui.QAction(MainWindow)
        self.actionListado_de_Personal_sin_Asignar_a_Secciones.setText(QtGui.QApplication.translate("MainWindow", "Listado de Empleados por Seccion", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Personal_sin_Asignar_a_Secciones.setObjectName(_fromUtf8("actionListado_de_Personal_sin_Asignar_a_Secciones"))
        self.actionAlta_de_Repuesto = QtGui.QAction(MainWindow)
        self.actionAlta_de_Repuesto.setEnabled(False)
        self.actionAlta_de_Repuesto.setText(QtGui.QApplication.translate("MainWindow", "&Alta de Repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Repuesto.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Repuesto.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite dar de alta un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Repuesto.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Repuesto.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Repuesto.setObjectName(_fromUtf8("actionAlta_de_Repuesto"))
        self.actionModificacion_de_Repuesto = QtGui.QAction(MainWindow)
        self.actionModificacion_de_Repuesto.setEnabled(False)
        self.actionModificacion_de_Repuesto.setText(QtGui.QApplication.translate("MainWindow", "&Modificación de Repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Repuesto.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Repuesto.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite modificar los datos de un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Repuesto.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para modificar los datos de un repuesto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionModificacion_de_Repuesto.setObjectName(_fromUtf8("actionModificacion_de_Repuesto"))
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion = QtGui.QAction(MainWindow)
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setEnabled(False)
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setText(QtGui.QApplication.translate("MainWindow", "&Registrar Recepción de Pedido de Actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar la recepción de un pedido de actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite registrar la recepción de un pedido de actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para registrar la recepción de un pedido de actuación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion.setObjectName(_fromUtf8("actionRegistrar_Recepcion_de_Pedido_de_Actuacion"))
        self.actionListado_de_Repuestos_de_la_Division = QtGui.QAction(MainWindow)
        self.actionListado_de_Repuestos_de_la_Division.setEnabled(False)
        self.actionListado_de_Repuestos_de_la_Division.setText(QtGui.QApplication.translate("MainWindow", "&Listado de Repuestos Solicitados", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Repuestos_de_la_Division.setObjectName(_fromUtf8("actionListado_de_Repuestos_de_la_Division"))
        self.actionAlta_de_Seccion = QtGui.QAction(MainWindow)
        self.actionAlta_de_Seccion.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/add_seccion.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAlta_de_Seccion.setIcon(icon17)
        self.actionAlta_de_Seccion.setText(QtGui.QApplication.translate("MainWindow", "&Alta de Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Seccion.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Seccion.setStatusTip(QtGui.QApplication.translate("MainWindow", "Permite dar de alta una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Seccion.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para dar de alta una sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_de_Seccion.setObjectName(_fromUtf8("actionAlta_de_Seccion"))
        self.actionAsignar_Reparacion = QtGui.QAction(MainWindow)
        self.actionAsignar_Reparacion.setEnabled(False)
        self.actionAsignar_Reparacion.setText(QtGui.QApplication.translate("MainWindow", "&Asignar Reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAsignar_Reparacion.setObjectName(_fromUtf8("actionAsignar_Reparacion"))
        self.actionRegistrar_Finalizacion_de_Reparacion = QtGui.QAction(MainWindow)
        self.actionRegistrar_Finalizacion_de_Reparacion.setEnabled(False)
        self.actionRegistrar_Finalizacion_de_Reparacion.setText(QtGui.QApplication.translate("MainWindow", "&Registrar Finalización de Reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRegistrar_Finalizacion_de_Reparacion.setObjectName(_fromUtf8("actionRegistrar_Finalizacion_de_Reparacion"))
        self.actionListados_de_Seccion = QtGui.QAction(MainWindow)
        self.actionListados_de_Seccion.setEnabled(False)
        self.actionListados_de_Seccion.setIcon(icon3)
        self.actionListados_de_Seccion.setText(QtGui.QApplication.translate("MainWindow", "&Listados de Sección", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListados_de_Seccion.setObjectName(_fromUtf8("actionListados_de_Seccion"))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division = QtGui.QAction(MainWindow)
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division.setText(QtGui.QApplication.translate("MainWindow", "Listado de Tipos de Reparaciones de la Division", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division.setObjectName(_fromUtf8("actionListado_de_Tipos_de_Reparaciones_de_la_Division"))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2 = QtGui.QAction(MainWindow)
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/recursos/iconos/car/list_reparaciones-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setIcon(icon18)
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setText(QtGui.QApplication.translate("MainWindow", "&Listado de Tipos de Reparaciones de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setToolTip(QtGui.QApplication.translate("MainWindow", "Haga click aquí para listar los tipos de reparaciones de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setStatusTip(QtGui.QApplication.translate("MainWindow", "Lista los tipos de reparaciones de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setWhatsThis(QtGui.QApplication.translate("MainWindow", "Haga click aquí para listar los tipos de reparaciones de la División", None, QtGui.QApplication.UnicodeUTF8))
        self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2.setObjectName(_fromUtf8("actionListado_de_Tipos_de_Reparaciones_de_la_Division_2"))
        self.actionAcerca_de_Division_de_Transporte = QtGui.QAction(MainWindow)
        self.actionAcerca_de_Division_de_Transporte.setText(QtGui.QApplication.translate("MainWindow", "&Acerca de \"División de Transporte\"", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de_Division_de_Transporte.setObjectName(_fromUtf8("actionAcerca_de_Division_de_Transporte"))
        self.actionPreferencias = QtGui.QAction(MainWindow)
        self.actionPreferencias.setText(QtGui.QApplication.translate("MainWindow", "&Preferencias", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferencias.setObjectName(_fromUtf8("actionPreferencias"))
        self.actionAlta_Tipo_de_Reparacion = QtGui.QAction(MainWindow)
        self.actionAlta_Tipo_de_Reparacion.setEnabled(False)
        self.actionAlta_Tipo_de_Reparacion.setText(QtGui.QApplication.translate("MainWindow", "Alta Tipo de Reparación", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAlta_Tipo_de_Reparacion.setObjectName(_fromUtf8("actionAlta_Tipo_de_Reparacion"))
        self.actionConsultar_agenda = QtGui.QAction(MainWindow)
        self.actionConsultar_agenda.setText(QtGui.QApplication.translate("MainWindow", "Consultar agenda", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConsultar_agenda.setObjectName(_fromUtf8("actionConsultar_agenda"))
        self.menuArchivo.addAction(self.actionCambiarDeUsuario)
        self.menuArchivo.addAction(self.actionAyuda)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuListados_de_Vehiculos.addAction(self.actionListado_Vehiculos_de_la_Division_2)
        self.menuListados_de_Vehiculos.addAction(self.actionListado_de_Reparaciones_Realizadas_a_un_Vehiculos_2)
        self.menuListados_de_Vehiculos.addSeparator()
        self.menuListados_de_Vehiculos.addAction(self.actionListado_Vehiculos_con_Reparaciones_Planificadas_2)
        self.menuListados_de_Vehiculos.addAction(self.actionListado_Vehiculos_con_Reparaciones_no_Planificadas_2)
        self.menuListados_de_Vehiculos.addSeparator()
        self.menuListados_de_Vehiculos.addAction(self.actionListado_Vehiculos_en_Reparacion_por_Seccion)
        self.menuListados_de_Vehiculos.addAction(self.actionListado_Vehiculos_Reparados_por_Seccion_2)
        self.menuVerificacion_y_Reparacion.addAction(self.actionAlta_de_Vehiculo)
        self.menuVerificacion_y_Reparacion.addAction(self.actionRegistrar_Ingreso_de_Vehiculo)
        self.menuVerificacion_y_Reparacion.addAction(self.actionRegistrar_Egreso)
        self.menuVerificacion_y_Reparacion.addAction(self.actionModificacion_de_Vehiculo)
        self.menuVerificacion_y_Reparacion.addSeparator()
        self.menuVerificacion_y_Reparacion.addAction(self.actionVerificar_Reparaciones_Necesarias_del_Vehiculo)
        self.menuVerificacion_y_Reparacion.addAction(self.actionPlanificar_Reparaciones_de_Vehiculo)
        self.menuVerificacion_y_Reparacion.addSeparator()
        self.menuVerificacion_y_Reparacion.addAction(self.menuListados_de_Vehiculos.menuAction())
        self.menuVerificacion_y_Reparacion.addAction(self.actionListado_de_Tipos_de_Reparaciones_de_la_Division_2)
        self.menuListados_Personal.addAction(self.actionListado_de_Personal_de_la_Division)
        self.menuPersonal.addAction(self.actionAlta_de_Personal)
        self.menuPersonal.addAction(self.actionBaja_de_Personal)
        self.menuPersonal.addAction(self.actionModificacion_de_Personal)
        self.menuPersonal.addSeparator()
        self.menuPersonal.addAction(self.actionCambiar_de_Seccion_a_un_Empleado)
        self.menuPersonal.addAction(self.actionCambiar_el_Encargado_de_una_Seccion)
        self.menuPersonal.addAction(self.actionRemover_Empleado_de_Seccion)
        self.menuPersonal.addSeparator()
        self.menuPersonal.addAction(self.menuListados_Personal.menuAction())
        self.menuListados_de_Repuestos.addAction(self.actionListado_de_Repuestos_de_la_Division)
        self.menuRepuestos.addAction(self.actionAlta_de_Repuesto)
        self.menuRepuestos.addAction(self.actionModificacion_de_Repuesto)
        self.menuRepuestos.addSeparator()
        self.menuRepuestos.addAction(self.actionRegistrar_Recepcion_de_Pedido_de_Actuacion)
        self.menuRepuestos.addSeparator()
        self.menuRepuestos.addAction(self.menuListados_de_Repuestos.menuAction())
        self.menuSecciones.addAction(self.actionAlta_de_Seccion)
        self.menuSecciones.addSeparator()
        self.menuSecciones.addAction(self.actionAlta_Tipo_de_Reparacion)
        self.menuSecciones.addAction(self.actionAsignar_Reparacion)
        self.menuSecciones.addAction(self.actionRegistrar_Finalizacion_de_Reparacion)
        self.menuSecciones.addSeparator()
        self.menuSecciones.addAction(self.actionConsultar_agenda)
        self.menuSecciones.addSeparator()
        self.menuSecciones.addAction(self.actionListados_de_Seccion)
        self.menuConfiguracion.addAction(self.actionPreferencias)
        self.menuAyuda.addAction(self.actionAcerca_de_Division_de_Transporte)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuVerificacion_y_Reparacion.menuAction())
        self.menubar.addAction(self.menuPersonal.menuAction())
        self.menubar.addAction(self.menuRepuestos.menuAction())
        self.menubar.addAction(self.menuSecciones.menuAction())
        self.menubar.addAction(self.menuConfiguracion.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())
        self.toolBar.addAction(self.actionAlta_de_Vehiculo)
        self.toolBar.addAction(self.actionModificacion_de_Vehiculo)
        self.toolBar.addAction(self.actionRegistrar_Ingreso_de_Vehiculo)
        self.toolBar.addAction(self.actionRegistrar_Egreso)
        self.toolBar.addAction(self.actionPlanificar_Reparaciones_de_Vehiculo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAlta_de_Personal)
        self.toolBar.addAction(self.actionBaja_de_Personal)
        self.toolBar.addAction(self.actionModificacion_de_Personal)
        self.toolBar.addAction(self.actionCambiar_de_Seccion_a_un_Empleado)
        self.toolBar.addAction(self.actionCambiar_el_Encargado_de_una_Seccion)
        self.toolBar.addAction(self.actionRemover_Empleado_de_Seccion)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSalir)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionSalir, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

import recursos_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

