# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WidgetMostrarReparacionesPorVehiculo.ui'
#
# Created: Thu Dec 11 22:27:06 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
# GUARNING! Se agregaron las siguientes tablas
from Utiles_formulario import TablaVehiculos, TablaReparaciones
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_WidgetMostrarReparacionesPorVehiculo(object):
    def setupUi(self, WidgetMostrarReparacionesPorVehiculo):
        WidgetMostrarReparacionesPorVehiculo.setObjectName(_fromUtf8("WidgetMostrarReparacionesPorVehiculo"))
        WidgetMostrarReparacionesPorVehiculo.setWindowModality(QtCore.Qt.WindowModal)
        WidgetMostrarReparacionesPorVehiculo.resize(1289, 620)
        WidgetMostrarReparacionesPorVehiculo.setMinimumSize(QtCore.QSize(988, 460))
        WidgetMostrarReparacionesPorVehiculo.setWindowTitle(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Mostrar Reparaciones Por Vehiculo", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(WidgetMostrarReparacionesPorVehiculo)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(WidgetMostrarReparacionesPorVehiculo)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Mostrar Vehiculos con reparaciones sin planificar", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Filtrar vehículo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_4)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit)
        self.horizontalLayout.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 73))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Filtro por fecha de finalización", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.dateEdit = QtGui.QDateEdit(self.groupBox_5)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.dateEdit)
        self.dateEdit_2 = QtGui.QDateEdit(self.groupBox_5)
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.dateEdit_2)
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(WidgetMostrarReparacionesPorVehiculo)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
#        self.tableWidgetReparaciones = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetReparaciones = TablaReparaciones(self.groupBox_2)
        self.tableWidgetReparaciones.setObjectName(_fromUtf8("tableWidgetReparaciones"))
        self.tableWidgetReparaciones.setColumnCount(5)
        self.tableWidgetReparaciones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Nombre", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Pertenece a la Orden", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Fecha Fin", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(4, item)
        self.tableWidgetReparaciones.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetReparaciones.horizontalHeader().setDefaultSectionSize(160)
        self.tableWidgetReparaciones.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetReparaciones.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetReparaciones, 1, 2, 1, 1)
#        self.tableWidgetVehiculos = QtGui.QTableWidget(self.groupBox_2)
        self.tableWidgetVehiculos = TablaVehiculos(self.groupBox_2)
        self.tableWidgetVehiculos.setMinimumSize(QtCore.QSize(600, 0))
        self.tableWidgetVehiculos.setMaximumSize(QtCore.QSize(600, 16777215))
        self.tableWidgetVehiculos.setObjectName(_fromUtf8("tableWidgetVehiculos"))
        self.tableWidgetVehiculos.setColumnCount(5)
        self.tableWidgetVehiculos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Dominio", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetVehiculos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Marca", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetVehiculos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Modelo", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetVehiculos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Registro Interno", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetVehiculos.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Chasis Nro", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetVehiculos.setHorizontalHeaderItem(4, item)
        self.tableWidgetVehiculos.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetVehiculos.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidgetVehiculos.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidgetVehiculos, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Vehiculos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("WidgetMostrarReparacionesPorVehiculo", "Reparaciones :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(WidgetMostrarReparacionesPorVehiculo)
        QtCore.QMetaObject.connectSlotsByName(WidgetMostrarReparacionesPorVehiculo)

    def retranslateUi(self, WidgetMostrarReparacionesPorVehiculo):
        item = self.tableWidgetReparaciones.horizontalHeaderItem(0)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(1)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(2)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(3)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(4)
        item = self.tableWidgetVehiculos.horizontalHeaderItem(0)
        item = self.tableWidgetVehiculos.horizontalHeaderItem(1)
        item = self.tableWidgetVehiculos.horizontalHeaderItem(2)
        item = self.tableWidgetVehiculos.horizontalHeaderItem(3)
        item = self.tableWidgetVehiculos.horizontalHeaderItem(4)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    WidgetMostrarReparacionesPorVehiculo = QtGui.QWidget()
    ui = Ui_WidgetMostrarReparacionesPorVehiculo()
    ui.setupUi(WidgetMostrarReparacionesPorVehiculo)
    WidgetMostrarReparacionesPorVehiculo.show()
    sys.exit(app.exec_())

