# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DialogRegistrarReparaciones.ui'
#
# Created: Sun Nov 25 16:33:42 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_DialogRegistrarReparaciones(object):
    def setupUi(self, DialogRegistrarReparaciones):
        DialogRegistrarReparaciones.setObjectName(_fromUtf8("DialogRegistrarReparaciones"))
        DialogRegistrarReparaciones.resize(740, 570)
        DialogRegistrarReparaciones.setMinimumSize(QtCore.QSize(740, 570))
        DialogRegistrarReparaciones.setWindowTitle(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Registrar Reparaciones de Vehiculo", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(DialogRegistrarReparaciones)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DialogRegistrarReparaciones)
        self.groupBox.setTitle(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Registrar Reparaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Buscar Vehiculo", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_3)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Dominio:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditDominio = QtGui.QLineEdit(self.groupBox_3)
        self.lineEditDominio.setObjectName(_fromUtf8("lineEditDominio"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditDominio)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.pushButtonBuscarVehiculo = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonBuscarVehiculo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonBuscarVehiculo.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Buscar Vehiculo", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBuscarVehiculo.setObjectName(_fromUtf8("pushButtonBuscarVehiculo"))
        self.verticalLayout_2.addWidget(self.pushButtonBuscarVehiculo)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tableWidgetOrdenesDeReparacion = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetOrdenesDeReparacion.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tableWidgetOrdenesDeReparacion.setObjectName(_fromUtf8("tableWidgetOrdenesDeReparacion"))
        self.tableWidgetOrdenesDeReparacion.setColumnCount(12)
        self.tableWidgetOrdenesDeReparacion.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Id Orden de Reparacion", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Fecha Ingreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Fecha Egreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Chofer Asignado", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Km Ingreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Km Egreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Equipamiento", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Combustible Ingreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Combustible Egreso", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Comisaria", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Revisada", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Planificada", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetOrdenesDeReparacion.setHorizontalHeaderItem(11, item)
        self.tableWidgetOrdenesDeReparacion.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_3.addWidget(self.tableWidgetOrdenesDeReparacion)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 300))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Reparaciones", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidgetReparaciones = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidgetReparaciones.setMaximumSize(QtCore.QSize(16777215, 150))
        self.tableWidgetReparaciones.setObjectName(_fromUtf8("tableWidgetReparaciones"))
        self.tableWidgetReparaciones.setColumnCount(6)
        self.tableWidgetReparaciones.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Tipo de Reparacion", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Descripcion", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Fecha Estimada de Inicio", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Fecha Inicio", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Fecha Fin", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Nro Orden", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidgetReparaciones.setHorizontalHeaderItem(5, item)
        self.tableWidgetReparaciones.horizontalHeader().setDefaultSectionSize(140)
        self.verticalLayout_4.addWidget(self.tableWidgetReparaciones)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 43))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonAgregarReparacion = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonAgregarReparacion.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButtonAgregarReparacion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonAgregarReparacion.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonAgregarReparacion.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Agregar una Reparacion", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAgregarReparacion.setObjectName(_fromUtf8("pushButtonAgregarReparacion"))
        self.horizontalLayout.addWidget(self.pushButtonAgregarReparacion)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBoxButtonBox = QtGui.QGroupBox(DialogRegistrarReparaciones)
        self.groupBoxButtonBox.setMinimumSize(QtCore.QSize(271, 41))
        self.groupBoxButtonBox.setMaximumSize(QtCore.QSize(16777215, 41))
        self.groupBoxButtonBox.setTitle(_fromUtf8(""))
        self.groupBoxButtonBox.setObjectName(_fromUtf8("groupBoxButtonBox"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBoxButtonBox)
        self.gridLayout_7.setContentsMargins(9, 9, 9, 8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.pushButtonAceptar = QtGui.QPushButton(self.groupBoxButtonBox)
        self.pushButtonAceptar.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Aceptar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAceptar.setObjectName(_fromUtf8("pushButtonAceptar"))
        self.gridLayout_7.addWidget(self.pushButtonAceptar, 0, 1, 1, 1)
        self.pushButtonCancelar = QtGui.QPushButton(self.groupBoxButtonBox)
        self.pushButtonCancelar.setText(QtGui.QApplication.translate("DialogRegistrarReparaciones", "Cancelar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancelar.setObjectName(_fromUtf8("pushButtonCancelar"))
        self.gridLayout_7.addWidget(self.pushButtonCancelar, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxButtonBox)

        self.retranslateUi(DialogRegistrarReparaciones)
        QtCore.QMetaObject.connectSlotsByName(DialogRegistrarReparaciones)

    def retranslateUi(self, DialogRegistrarReparaciones):
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(0)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(1)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(2)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(3)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(4)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(5)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(6)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(7)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(8)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(9)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(10)
        item = self.tableWidgetOrdenesDeReparacion.horizontalHeaderItem(11)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(0)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(1)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(2)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(3)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(4)
        item = self.tableWidgetReparaciones.horizontalHeaderItem(5)


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    DialogRegistrarReparaciones = QtGui.QDialog()
    ui = Ui_DialogRegistrarReparaciones()
    ui.setupUi(DialogRegistrarReparaciones)
    DialogRegistrarReparaciones.show()
    sys.exit(app.exec_())

